### ISSUE TITLE
Ignores click events until popup showed

### ISSUE THREAD

**Issue by inf3rno** [jake-phy/WindowIconList#101]
It does not always open the application by pressing the button, I have to try sometimes 4 times. This is because the applet waits for the popup with the application name to appear. Before that it ignores your clicks.

**Comment by mbacou** [comment]
Yes, same problem -- not always as snappy as you'd expect, end up clicking the same app icon several times as well.

**Comment by TurkeyMan** [comment]
I have this same problem, makes this borderline unusable.
I also get into this state when the clicks aren't working, that the pinned task buttons enter rearranging/move mode, and they start drag around when I'm just trying to activate that app.

**Comment by samogot** [comment]
@TurkeyMan, what you discribe is more looks like another bug #92. `cinnamon --replace&` helps in this case

**Comment by TurkeyMan** [comment]
This is the critical bug, because it makes it almost unusable. That one is secondary.

**Comment by jake-phy** [comment]
I have just uploaded another version.   Is this fixed in it?  I am going to try to get this stable and then let someone else take over for development so hopefully bugs will get fixed quicker here in the near future.

**Comment by TurkeyMan** [comment]
Seems to be working well for me now.
Thanks for this tool, I'd struggle to use Cinnamon without it!
Do you have someone lined up, or is this at risk of going dormant?

**Comment by jake-phy** [comment]
I don't have anyone so it is at risk.   but with the number of bugs that I was able to fix yesterday and today i think I'm ready for release.
