### ISSUE TITLE
Windows sometimes require 2 clicks to open instead of 1

### ISSUE THREAD

**Issue by frane-giscloud** [jake-phy/WindowIconList#106]
Windows sometimes require 2 clicks to open instead of 1.

OS: Linux mint 17.2
Cinnamon: 2.6

**Comment by frane-giscloud** [comment]
I've taken a peak, and saw that the _onAppButtonRelease doesn't get triggered on unopened favorites.
Only for the first time, but then it works fine.

**Comment by frane-giscloud** [comment]
The issue is resolved:
```
344c344
<         this.parentActor.connect('button_press_event', Lang.bind(this, this._onButtonPress));
---
>         this.parentActor.connect('button-release-event', Lang.bind(this, this._onButtonPress));
349c349
<         this.actor.connect('button_press_event', Lang.bind(this, this._onButtonPress));
---
>         this.actor.connect('button-release-event', Lang.bind(this, this._onButtonPress));
```

You only need to change the event in SpecialMenus,js from button-release-even > button_press_event.

**Comment by samogot** [comment]
this issue is dublicate of #101 
@frane-giscloud, thx for the fix

**Comment by jake-phy** [comment]
Confirmed fixed, thanks for implementing that guys.
