### ISSUE TITLE
Title Display Focused doesn't resize Title on close of App

### ISSUE THREAD

**Issue by AVellucci** [jake-phy/WindowIconList#107]
When using the **Title Display** *Focused* 
the windows titles don't always resize.
This happens mostly when the app is closed, the panel doesn't seem to recognize it's no longer the active panel and lock it to remain open.
if I switch between open windows the closed app icon is still sized as if the app was still open and active and it doesn't reclaim the empty space. opening and closing multiple apps creates massive empty space on the panel taskbar.
I have to reopen the app, select another app to be active then close the app without setting it active to make sure the title doesn't stay open.
![screenshot from 2015-11-12 12 16 49](https://cloud.githubusercontent.com/assets/11682773/11125416/d3fad25c-8937-11e5-83f4-4918cdb901c5.png)

**Comment by jake-phy** [comment]
Yes that is a bug that is currently fixed in the dev version.  however it isn't quite done yet as now they are not the nice uniform size.

**Comment by jake-phy** [comment]
Alright everything should be good now.
