### ISSUE TITLE
keyboard block when preview is active

### ISSUE THREAD

**Issue by samogot** [jake-phy/WindowIconList#108]
when popup is active (with or without thumbnail) keybord typing didnt work for active window, nor even global system shortcuts

**Comment by jake-phy** [comment]
I don't think there is anyway to avoid that.  I am using the popmenu's to create the thumbnails and they by default steal the focus.  I'll see if I can find away around that, but as of now not much I can do.

**Comment by jake-phy** [comment]
This has actually been fixed by another developer.  #123.
