### ISSUE TITLE
Uniformly sized buttons

### ISSUE THREAD

**Issue by TurkeyMan** [jake-phy/WindowIconList#112]
One minor detail that really bugs me, is that all the task buttons are different sizes depending on the length of the title of the window. I would find it so much more visually pleasing if they were all the same size; expanded to the same maximum size as they're limited now when the titles are long, and all shrank uniformly as the taskbar became over-full.

**Comment by jake-phy** [comment]
related #107

**Comment by jake-phy** [comment]
Alright this should be fixed in the latest dev.  I think I am pretty much ready for release.

**Comment by TurkeyMan** [comment]
Perfect, thanks!
