### ISSUE TITLE
Rearranging pinned apps on the taskbar is really clunky

### ISSUE THREAD

**Issue by TurkeyMan** [jake-phy/WindowIconList#116]
Grab a pinned app, drag it around the taskbar to rearrange its position... notice that the behaviour is really clunky; it's imprecise, jerky, and often leads to weird jittering as apps rapidly toggle either side of the thing you're moving. It's also really hard to get it go where you're actually hovering, it's like you're fighting against some weird placement logic (latest dev is much better than it was).
At very least, it should not jitter and jump around, ideally fitting in between the closest gap to the mouse cursor. It would be nicer still if it felt a bit more modern and the other buttons animate/slide into relative position as you drag an item around.

**Comment by jake-phy** [comment]
your right.  I'll see what I can do.  an animation would be really nice.

**Comment by TurkeyMan** [comment]
I've also noticed that pinned apps have a tendency to not remember where I put them...
It may be user error, but I tend to think the position of pinned apps should be eagerly recorded, and there shouldn't be cases where it forgets and reverts to prior state.

**Comment by jake-phy** [comment]
Are you using the dev?  I'm having a 100% success moving pinned apps and there are no errors getting outputted.

**Comment by TurkeyMan** [comment]
I'm from dev a couple of days ago... you don't find that it gets in a state where it jitters between either side of the item you're moving?
I'll get latest tonight and try again.

**Comment by jake-phy** [comment]
Alright I just now have made a few changes and added an animation.  Still isn't quite were I like it though.  I see what you mean by the jitter.  Thing is, I used the Cinnamon menu to figure the favorites out and that can tend to jitter too.

**Comment by TurkeyMan** [comment]
Just got latest, animation will definitely be a nice improvement, but it only seems to work in one direction right now. It works nicely if I grab an icon and move it left, but if I move it right, it snaps ;)

Jitter is much better, but I can still make it happen sometimes. I'm noticing a new jitter-related behaviour though; in lieu of position jitter, a button with a long label truncated with '...' is also jittering the text. It seems the label string itself jitters between rendering the '...' on the end, and rendering as much of the actual text that fits in the button space. Kinda hard to describe, but I'm sure you can see it too if you drag around a button with a truncated name.

**Comment by jake-phy** [comment]
Alright so the main jitter should be fixed now and the drag should work just fine.  Math is complicated and my head hurts but it works :).  As far as the text jitter I have noticed it but as it is a redraw issue, I'm going to ignore it for now.  Would you be willing to open a new bug for that?

**Comment by TurkeyMan** [comment]
Latest dev is much better. I see minor jittering, but it doesn't interfere with functionality, it just looks a bit rough. I'll open a new issue for that.

Thanks!
