### ISSUE TITLE
It's difficult to move a window to the far right

### ISSUE THREAD

**Issue by TurkeyMan** [jake-phy/WindowIconList#119]
Grab an app button and drag it around, you'll notice that it's hard (sometimes impossible) to drop the button on the far right. Buttons always seem to prefer to position themselves to the left of buttons they hover above. I'm sure this is related to the behaviour where the animation only works smoothly in one direction, and you're already on it... but just thought it should be logged.

**Comment by jake-phy** [comment]
this should be fixed now.

**Comment by TurkeyMan** [comment]
Just updated... I'm getting all sorts of weird behaviour now.

Firstly, with "Arrange pinned apps" disabled, most of the time I click on a task button to select an app, the app icon sticks to the mouse cursor and I can drag it around the screen and drop it on things, and the taskbar doesn't really work properly. It's hard to describe, but it's really broken.
Now, if I enable "Arrange pinned apps" to test this bug, I can't really see that it's any better than it was, still hard to get my app on the right, but then the effect I mentioned above is already acting at the same time, so it's hard to see the behaviours separate from eachother.

I'm really wondering if my update failed somehow... is there some settings recorded somewhere that may be in an invalid state on my machine perhaps? The install script should probably wipe any residual settings.

A side note, I can't find a way to identify which version is running. Can we have an 'about' or something somewhere to verify the right version is installed and in use (develop branch installs should probably list the git hash)?

**Comment by jake-phy** [comment]
Ok so i just changed the version on my machine to todays timestamp, can you try it now to make sure you have the correct version?  Also try removing the applet using the configure script and then installing it.

**Comment by TurkeyMan** [comment]
Deleted everything, started over with latest develop branch. Broken behaviour fixed, topic of this issue is definitely substantially improved.
This issue is now hindered by some minor weird jiggling, but that's logged as a separate issue, I'll close this until that one is resolved, and then revisit this issue if it remains relevant.
Thanks!

**Comment by nyanpasu64** [comment]
Related: The applet does not expand to fill empty space. If I try to drag an icon beyond the last icon in the list + one empty space, the applet shows a "X" cursor, and no longer moves the window when you let go.
