### ISSUE TITLE
Thumbnails displayed through popupMenu causes temporary loss of focus.

### ISSUE THREAD

**Issue by repsac-by** [jake-phy/WindowIconList#120]
Thumbnails displayed through popupMenu causes temporary loss of focus when you hover on buttons of applications on the panel. Sometimes this behavior is not desirable, such as Tilda(terminal)  configured to hide when losing focus, disappears if you accidentally hover the mouse on the application button.

"Open ThumbnailS onClick" is not working or does not work as I expect.

**Comment by jake-phy** [comment]
that is a problem.  I'm not sure if I can fix it or not :/ right now I'm using the inbuilt popup menu which automatically grabs focus.

**Comment by repsac-by** [comment]
I removed(commented) this line [applet.js#L355](https://github.com/jake-phy/WindowIconList/blob/master/WindowListGroup%40jake.phy%40gmail.com/applet.js#L355) and now there is no loss of focus. This solved my problem, now everything works as I expect. Yet to be discovered side effects.

**Comment by jake-phy** [comment]
Hmm that is very interesting.  I never thought of that.  The only thing that happens is the menu no longer is closed when clicked of it, but that shouldn't matter with the thumbnails.  Do you want to open a pull request so I can put you down as a contributer?

**Comment by repsac-by** [comment]
https://github.com/jake-phy/WindowIconList/pull/123
