### ISSUE TITLE
Selecting a window via thumbnail freezes for a moment

### ISSUE THREAD

**Issue by TurkeyMan** [jake-phy/WindowIconList#122]
Open a few instances of an app; 3 nemo windows for instance.
Hover over the nemo taskbutton, 3 thumbnails appear. Hovering over each of them reveals the window (hiding other windows), this works well, and very fast. Middle-click closes the instance, also very fast. But left-click on the desired instance to bring it to front and note that there is a decent freeze before your desktop returns.
I don't recall seeing this in prior versions.

**Comment by jake-phy** [comment]
Alright can you try this version and see if it is fixed?  I don't think it was frozen per-say, it is just I was adding the hover timeout on the window open which was not good.

**Comment by TurkeyMan** [comment]
It feels like it's improved, I'd say it's acceptable now, but it's still not as instantaneous as the other actions I listed above for comparison.

**Comment by TurkeyMan** [comment]
I'll close this, since I think it's fine, but I wonder if it could be a touch better.

**Comment by jake-phy** [comment]
Yeah I'll lower the timeout.  Having the timeout at all was probably an oversight by me.

-----Original Message-----

**Comment by jake-phy** [comment]
So i have taken the timeout off completely now.   Should be pretty much just as fast.
