### ISSUE TITLE
Firefox weird behaviour

### ISSUE THREAD

**Issue by manofthepeace** [jake-phy/WindowIconList#125]
Using latest version from github, as soon as I touch the firefox icon it goes into the "icon moving mode" without clicking, so wherever I move the mouse on the screen I see the firefox logo until I press ESC. Only that app is doing that not sure why though, even if located somewhere else.

**Comment by jake-phy** [comment]
Can you confirm which version you have?  

-----Original Message-----

**Comment by manofthepeace** [comment]
I am not to sure of the exact version of the applet itself, but I took the zip file from the master branch in git, my firefox is version 43.0.

**Comment by jake-phy** [comment]
Ok try the dev branch.  I will be updating the master branch this evening.

-----Original Message-----

**Comment by manofthepeace** [comment]
That fixed it! Many thanks, not related to that issue, but on that version the pin/unpin in very slow. after unpin I have to hover on the icon I just unpinned in order for it to disappear. Is it a known behaviour?
