### ISSUE TITLE
bring back the option to disable "group apps into single icons"

### ISSUE THREAD

**Issue by GitHorst** [jake-phy/WindowIconList#136]
In the current dev branch, the icons in the "title" view now all have equal width, which is very nice.
#112 was a related issue report.

Unfortunately, now all windows of one program are hidden in one icon in the panel. This way, switching between the different windows takes much longer, since you first have to bring up the preview thumbnails, then find the window you want to switch to, then click on it. 

It would be great to have the previously existing option to disable "group apps into single icons" back.

As a related suggestion: It would be nice to additionally have the choice of what shall happen when the panel gets too full. With option a) shrink all icons proportionally, b) merge all windows of a program into a single item, c) ...?
Or maybe even be able to define a limit until when icons are shrunk and after which they will be merged into a single one.

**Comment by GitHorst** [comment]
suggestions in the 2nd part are related to #130 as well

**Comment by jake-phy** [comment]
Yes but that was going to be part of a separate app.  I had decided to split the two up, but that is turning out to be harder plus it does not help with the speed like I had hoped it would.  I shall merge them back together again :) I'll see about part two.  i know the default window list does that though I'm not sure how.

**Comment by lukaszpolowczyk** [comment]
@jake-phy How quickly you can do it to restore?
That to me is the most important function.

**Comment by jake-phy** [comment]
Hi Guys, both these bugs should be fixed now.

**Comment by lukaszpolowczyk** [comment]
@jake-phy Current fixes works fine.

**Comment by GitHorst** [comment]
Hey!
this looks very nice indeed. You decided to shrink only the width of the icons of the app that takes too much space in the panel, which seems reasonable, looks good and works well ;)
Thanks for all your efforst -- to me this applet is very useful for working more efficiently.
Cheers!

ps, i wasn't sure whether it was necessary but to be on the safe side i first uninstalled the old "dev-branch-installation" using your .py script. after reinstalling the new one, the settings were still there (the apps linked in the panel and their order). just mentioning this, in case you would like to make it a "purge" type of uninstall.

**Comment by GitHorst** [comment]
not sure whether i am supposed to do this but i will close the issue. thanks again!

**Comment by gmaggio** [comment]
Just wondering but is the "un-grouping" issue fixed? 'Cause I can't seem to get it to work.

**Comment by ncelerier** [comment]
Hello gmaggio, 

It looks like it is working for me. 

Did you try with the latest version from the develop branch ?

**Comment by gmaggio** [comment]
Oh.. sorry.. I wasn't testing the development branch. I thought it was already in production.
