### ISSUE TITLE
Please remove 1px margin-bottom under this aplet.

### ISSUE THREAD

**Issue by lukaszpolowczyk** [jake-phy/WindowIconList#138]
Please remove 1px margin-bottom under this aplet.
1px margin-botton on bottom screen edge not response on click launchers.
Launchers should be clickable on bottom screen edge.

**Comment by jake-phy** [comment]
Hi This should be fixed in the dev version.  Can you confirm that you are using the Mint Applet Repository version?

**Comment by lukaszpolowczyk** [comment]
I use version from: Applets > "Allow applets (online)". In there is this bug.
