### ISSUE TITLE
some JS Errors

### ISSUE THREAD

**Issue by im-kulikov** [jake-phy/WindowIconList#23]
JS ERROR: !!!   WARNING: 'anonymous function does not always return a value'
    JS ERROR: !!!   WARNING: file '/usr/share/cinnamon/js/ui/expoThumbnail.js' line 702 exception 0 number 157
Предупреждение менеджера окон: Log level 16: Unable to register authentication agent: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: An authentication agent already exists for the given subject
Предупреждение менеджера окон: Log level 16: Error registering polkit authentication agent: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: An authentication agent already exists for the given subject (polkit-error-quark 0)
    JS ERROR: !!!   WARNING: 'anonymous function does not always return a value'
    JS ERROR: !!!   WARNING: file '/usr/share/cinnamon/applets/WindowListGroup@jake.phy@gmail.com/applet.js' line 474 exception 0 number 157
    JS ERROR: !!!   WARNING: 'anonymous function does not always return a value'
    JS ERROR: !!!   WARNING: file '/usr/share/cinnamon/applets/WindowListGroup@jake.phy@gmail.com/specialButtons.js' line 433 exception 0 number 157
    JS ERROR: !!!   WARNING: 'anonymous function does not always return a value'
    JS ERROR: !!!   WARNING: file '/usr/share/cinnamon/applets/WindowListGroup@jake.phy@gmail.com/specialButtons.js' line 446 exception 0 number 157
Предупреждение менеджера окон: Treating resize request of legacy application 0x1e00004 (tilda) as a fullscreen request
Предупреждение менеджера окон: Log level 16: gsignal.c:2576: instance `0x2f06f00' has no handler with id `20281'
Предупреждение менеджера окон: Log level 16: gsignal.c:2576: instance `0x2f06f00' has no handler with id `20282'
Предупреждение менеджера окон: Treating resize request of legacy application 0x1e00004 (tilda) as a fullscreen request

**Comment by jake-phy** [comment]
I have the anonymous functions resolved now.
