### ISSUE TITLE
Window select inadequate for large numbers of windows

### ISSUE THREAD

**Issue by thoughtafter** [jake-phy/WindowIconList#26]
With hover peek disabled, when hovering over an icon I get a horizontal list of windows that on my display can show about 6 windows in their entirety. When more than 6 windows are present (common for web browsers) there is no way to select individual windows without running scale or expose. A better solution would be to display a vertical list of window titles once the number of windows is too large for the horizontal display. This is what most desktops do in this regard.

**Comment by jake-phy** [comment]
These issues should all be fixed now.  I have added a way of stacking thumbnails and the memory has been about 2 kb for each thumbnails.
