### ISSUE TITLE
Make icon click work similar to windows

### ISSUE THREAD

**Issue by VanCoding** [jake-phy/WindowIconList#42]
Under windows, when I left-click the app icon, there are 3 cases:

- the app is not open yet -> start the app
- the app is open once -> show the window of the app
- the app is open multiple times -> show the previews of all windows

In this applet though, the case with multiple open windows is different. It still shows/hides one window of the app while ignoring the others. But this does not make sense to me. If one window is open, I don't care about the previews so I can wait the timeout before the icons get shown. But when there are multiple windows, I want to be able to switch to my chosen window as fast as possible. So getting the preview list on a click is much faster than waiting for the timeout.

What do you think?

**Comment by jake-phy** [comment]
Option has been added in the settings for this.
