### ISSUE TITLE
Turning off always on visible can crash cinnamon

### ISSUE THREAD

**Issue by pahaloom** [jake-phy/WindowIconList#50]
Open two windows of a pinned application (have a group with a number 2)
Right click on a group and select "Visible on all workspaces"
Switch to other workspace (ctrl+alt+arrow)
Close the window that was still visible (notice that only the last active window of the group actually got displayed on other workspace)
Right click again on a group and select "Visible only current workspace"

Result: cinnamon crash

Cinnamon v2.2.16 on linux mint 17. Window list plugin installed via "Get more online" at applets setting.

**Comment by jake-phy** [comment]
this should be fixed in the dev.
