### ISSUE TITLE
"Random" highlighting of icons

### ISSUE THREAD

**Issue by JakubRimal** [jake-phy/WindowIconList#51]
I found that sometimes some app icons are highlighted when they shouldn't be.

How to reproduce it:
1. start some apps (for example I have opened Firefox, Banshee, Skype, Sublime and Thunderbird)
2. go to Thunderbird (or other app...) and click on some link which will be opened in Firefox
3. Icons for Banshee, Skype and Sublime are highlighted.
![snimek obrazovky porizeny 2014-08-30 22 40 48](https://cloud.githubusercontent.com/assets/2625056/4100162/f700e90a-3085-11e4-96c1-4938edb97a14.png)

What "highlighted" means:
Icons will have style of "window-list-item-demands-attention" class, which is defined in ~/.themes/yourTheme>/cinnamon/cinnamon.css

Because it is really annoying, I have commented out definition of "window-list-item-demands-attention" class as a workaround.

Version info:
Window List with App Grouping 2.7.5
Linux Mint 17 Cinnamon 64-bit

**Comment by jake-phy** [comment]
Are you willing to test the Dev branch again?  I can't get the notifications to even work for the normal window list.  Not sure what is wrong.

**Comment by JakubRimal** [comment]
Yes, I can confirm that it probably doesn't work in default Window List applet, so I think that it can't work with your applet.
But for me is Window List with App Groupin unusable now because of it does no action onclick on app icon. So now I use default Window List applet.
Thank you for your work!

**Comment by jake-phy** [comment]
You can change that in the settings :).

-----Original Message-----

**Comment by JakubRimal** [comment]
Sorry, I have no idea how to do it. It looks like click doesn't work during animation of showing of thumbnail. This is probably the only one settings how to avoid this very uncomfortable behaviour:
![snimek obrazovky porizeny 2015-03-16 22 17 20](https://cloud.githubusercontent.com/assets/2625056/6676735/717c5ecc-cc2a-11e4-8864-29454cc98b90.png)

**Comment by jake-phy** [comment]
Weird it looks like everything is right there.  One other user reported that the windows are not opening right away when they clicked.

-----Original Message-----

**Comment by JakubRimal** [comment]
Ok after some tests it seems like it really depends on Thumbnail timeout setting – when I click around the time which is set in the settings, the click has no action.

**Comment by jake-phy** [comment]
You know what that could be.  I never thought of that!!!  I'll look into it this evening.

-----Original Message-----

**Comment by JakubRimal** [comment]
> Are you willing to test the Dev branch again? I can't get the notifications to even work for the normal window list. Not sure what is wrong.

Now I know how to get notifications: in Pidgin go to Tools > Plugins and enable Message notification plugin (not sure the exact name because I have it in Czech). After that Window list should get the *.window-list-item-demands-attention* CSS class when new message appears.

**Comment by jake-phy** [comment]
This has been fixed in dev.
