### ISSUE TITLE
Other things

### ISSUE THREAD

**Issue by lestcape** [jake-phy/WindowIconList#59]
Your applet it's not a panel launcher without this: "role": "panellauncher", in the metadata.json file.
```
 "max-instances": 2,
"uuid": "WindowListGroup@jake.phy@gmail.com",
"name": "Window List With App Grouping",
+"role": "panellauncher",
"version": "2.7.5",
"description": "Window List with App Grouping an Window Thumbnails"
}
```
In the applet.js
PinnedFavs.prototype = {

It's a wrong procedure, modify a value of settings and wait for a settings change to reload app... XletSettings react very slow...

- this._applet.settings.connect('changed::pinned-apps', Lang.bind(this, this._reload));
+ this._applet.settings.connect('changed::pinned-apps', Lang.bind(this, function() { this._onFavsChanged(); } ));

**Comment by jake-phy** [comment]
Hey Lester I ran into an issue with the "role" ,"panellauncher" in the Schema.json throwing an error.  Any idea why?

**Comment by jake-phy** [comment]
You name is Lester right?

**Comment by lestcape** [comment]
I have this version of your applet for a long time ago without any error... I also download the new merge version rigth now and i don' t have any problem.

**Comment by jake-phy** [comment]
I'm currently using cinnamon 2.4 i think.  that is where the issue was coming in.

**Comment by lestcape** [comment]
The possibility of integrate the the applet with cinnamon is only on cinnamon 2.4 or higer, that was mtwebstern make the change to allow that... So, yes you need cinnamon 2.4 to work property...

Zagor... is a friends and he create several themes for cinnamon, like zukito, also he is who update others good themes.. He said me that share with you the possibility to create an stylesheld file with the applet selector, to can be used on her themes.

https://plus.google.com/u/0/106773314255716729881/posts/WWoTQMpm7ce

**Comment by jake-phy** [comment]
I would love to create a style sheet for the applet.  The only thing, I have no idea how to implement it.  Do you have any pointers?

-----Original Message-----

**Comment by lestcape** [comment]
There are no reference, as my know.  What i do, is place a default selector, taking one thats is supported on cinnamon, searching for the standard cinnamon css file. Then, i create a new one thats is not on cinnamon, and override the theme with this one. What occurs is that my local style will not be apply, because the global style have preference, so only allow theme authors to see the selector and implement this on the global themes (on that case as is global will be apply). The restriction is that the new selector need override all features of the default selector and the new selector need to be placed after the default one on the css file to can be apply correctly.

Thats is an example:
```
   // cinnamon selector (default)
   this.actor.set_style_class_name('menu-application-button-selected');
   // my new selector (to override the default)
   this.actor.add_style_class_name('menu-removable-button-selected');
```

**Comment by jake-phy** [comment]
Ok I'll see what I can come up with.

**Comment by zagortenay333** [comment]
Awesome!

**Comment by jake-phy** [comment]
Hi Lester, I have finally re-enabled this.  Works great.
