### ISSUE TITLE
when middle click on a preview to close the window, other previews for the same app should remain visible

### ISSUE THREAD

**Issue by TurkeyMan** [jake-phy/WindowIconList#63]
currently, if you have 3 copies of the same app open, there are 3 previews beside eachother. let's say you want to close 2 of them; you hover till the previews are visible, then you want to middle-click the 2 that you want to close.
the problem is that when you middle-click one, the previews disappear, and you need to move the mouse, and hover to make it appear again.
please fix to that the previews remain visible, so you can close multiple windows at once.

**Comment by jake-phy** [comment]
Yes I am working on this.

**Comment by jake-phy** [comment]
This is fixed in the development branch.  :)

**Comment by TurkeyMan** [comment]
Yay! Thanks!

**Comment by jake-phy** [comment]
Not quite fixed actually.  the hover peek effect is messing with it.  I'll get that fixed.

**Comment by jake-phy** [comment]
there fixed right.
