### ISSUE TITLE
when task buttons have labels, the buttons are all different sizes (sized to fit label)

### ISSUE THREAD

**Issue by TurkeyMan** [jake-phy/WindowIconList#64]
i really don't like how the task buttons with labels visible are all different sizes. there seems to be a maximum size when window labels are long. please add an option to make all buttons this size, unless the bar is full, then they should all be scaled down proportionally together.

**Comment by jake-phy** [comment]
I don't think i can make the labels scale down?  But I have added an setting to control the menu width.  Does that work?

**Comment by TurkeyMan** [comment]
Situation is much better. Closing.
