### ISSUE TITLE
Use a branching model for stability

### ISSUE THREAD

**Issue by Beanow** [jake-phy/WindowIconList#66]
I would like to make some small modifications to the most recent release, I would need to revert my working tree to your release commit manually. Perhaps you could consider [git flow](http://nvie.com/posts/a-successful-git-branching-model/).

**Comment by jake-phy** [comment]
That is a great idea.  I will see about implementing a development branch.

**Comment by jake-phy** [comment]
Ok I have a simple version of this built up.  Think it will work?

**Comment by Beanow** [comment]
Not quite, only master and develop are permanently present.
The others are temporary when you need them.
For example: release/1.1.0, hotfix/1.0.3, feature/new-shortcuts

**Comment by jake-phy** [comment]
Ahh I see.  That makes sense.  

-----Original Message-----

**Comment by Beanow** [comment]
Seems implemented like this.
