### ISSUE TITLE
Add support for LauncherAPI

### ISSUE THREAD

**Issue by Rezonansowy** [jake-phy/WindowIconList#68]
Unity's LauncherAPI support would be very useful for everyone. Here's an official doc on it – https://wiki.ubuntu.com/Unity/LauncherAPI It will be great if it will read LauncherAPI entries from applications' .desktop files.

It's appearance is similar to JumpLists form Windows taskbar.

Here's how it looks in Windows:
![jumplists_thumb](https://cloud.githubusercontent.com/assets/6929363/5031825/d54d30b6-6b59-11e4-88c2-d90eadbe1a5d.png)

And it's implemented in Unity, DockbarX, Cairo Dock and probably GNOME Shell.

Here's how it looks in Ubuntu Unity:
![image_thumb8](https://cloud.githubusercontent.com/assets/6929363/5031943/7e4154a4-6b5a-11e4-9ac1-71ad99e0a6f8.png)

**Comment by lestcape** [comment]
Yes, gnome shell have an implementation of this that can be see here:
https://github.com/rgcjonas/gnome-shell-extension-appindicator

**Comment by jake-phy** [comment]
This is implimented in the dev branch.  Hope to release soon.
