### ISSUE TITLE
Your applet is too awesome

### ISSUE THREAD

**Issue by robzan8** [jake-phy/WindowIconList#76]
Seriously, this was the only thing I missed form windows. I switched from my long time love Xfce to Cinnamon just for this.
I would like to suggest one minor improvement though: when you have multiple (say gedit) windows opened, then you go over with the mouse and it shows a preview of the windows, then you close one window directly form the preview, it would be super nice if the applet would stay in preview mode to let you close also other windows eventually (it does this on microsoft windows).
Congratulations for the good job by the way :)

**Comment by jake-phy** [comment]
Thanks :)  your request is already in the works.

**Comment by robzan8** [comment]
Great

**Comment by jake-phy** [comment]
commit 571673 has these changes in it :)

**Comment by robzan8** [comment]
Wow, didn't expect it to be so much work :)

**Comment by jake-phy** [comment]
Yeah well you gotta do what you gotta do.
