### ISSUE TITLE
Error this.appInfo.list_actions is not a function

### ISSUE THREAD

**Issue by den-eimai** [jake-phy/WindowIconList#80]
I'm running cinnamon 2.0.14(LMDE) and after i installed the applet from here, i get the above notification from cinnamon. The applet is shown as added to panel from the Applets Settings, and i can edit the configuration, but nothing shows up in the panel (except when i click Highlight while configuring it).

**Comment by jake-phy** [comment]
Hmm not good.  Thanks for bringing that to my attention.  I'll have to wrap it in a try statement.

-----Original Message-----

**Comment by lestcape** [comment]
I think that is not possible keep the compatibility on some cases. LMDE and Ubuntu don't have the same version... @den-eimai I think that you need to use an old version as cinnamon is...

**Comment by jake-phy** [comment]
Ok this should be fixed now on the development branch.  can you test?  The actions will not show, but the applet should still work.

**Comment by den-eimai** [comment]
Yes it's fixed, thanks.
 It has a new minor bug though. When the Title Display is set to
focused, it actually shows title.

jake-phy:
> Ok this should be fixed now on the development branch.  can you test?  The actions will not show, but the applet should still work.

**Comment by jake-phy** [comment]
This should be fixed now.  Thanks for bringing it to my attention.  I never use half the stuff i have implemented :)  So sometimes stuff breaks without me knowing it.
