### ISSUE TITLE
Applet not respecting desktop effects setting for minimize.

### ISSUE THREAD

**Issue by ronasimi** [jake-phy/WindowIconList#81]
I've got the minimize animation set to "Traditional" but for some reason when using this applet it always uses "Scale".  My guess is that the applet isn't registering as a task list in cinnamon, so the shell doesn't know where to draw the minimize animation.

**Comment by jake-phy** [comment]
I have not been able to figure this one out.  it would seem like it is hard coded in cinnamon some where.

**Comment by jake-phy** [comment]
Finally figured out how this works.  Minimize and maximize should be animating correctly now.

**Comment by GitHorst** [comment]
@jake-phy : i still observe the same behavior as described in the OP. even with the dev version.

I have cinnamon "Window effects" switched on and the "Effects style" set to "Cinnamon" (which uses the "Traditional" animation for minimizing windows).
When I use the (cinnamon standard) "Window list" applet, the animation works as it should. With your applet, the "Traditional" minimize animation does not work, but shows the "Scale" animation instead. All the other animations work as they should!

**Comment by jake-phy** [comment]
Alright can you test the latest version?  One thing, you can't run the cinnamon window list side by side with this one, as the cinnamon list will steel the animation.  Also I hadn't had it working when the windows were unstacked.  Hopefully it works now.

**Comment by GitHorst** [comment]
@jake-phy: perfect! thanks again for all your work! 
ps, i have no idea how these things are organized but you should try to have this integrated into Linux (Mint? (Cinnamon? ;))) at some point. The standard window list there is a pain :P
