### ISSUE TITLE
show thumbs always below applet fails on lower panel

### ISSUE THREAD

**Issue by stefan123t** [jake-phy/WindowIconList#82]
Dear Jake,
probably something easy to fix, I tried placing the applet on the lower panel.
When hovering nothing is displayed, as the thumbs are probably placed below the panel in the part of the screen not visible.
Your applet would either need to check whether it is placed in the upper/lower panel (or a left/right panel in future ?) or provide a setting to make thumbs/menus appear below/above the applet (right/left of in future).
Kind regards,
Stefan

**Comment by jake-phy** [comment]
Hi Stefan, have you tried restarting  cinnamon after moving the applet?  It probably did not switch the orientation when it was moved.
  Another thing to add to my list.  

-----Original Message-----

**Comment by stefan123t** [comment]
yes, you are right that worked for me.
thanks for this really nice applet!

**Comment by jake-phy** [comment]
This is now fixed on the development branch.   You can drag to the bottom without having to restart cinnamon.
