### ISSUE TITLE
In "Classic" panel mode, thumbnails don't show up if on bottom panel

### ISSUE THREAD

**Issue by anandtrex** [jake-phy/WindowIconList#86]
When I set my panel configuration to "Classic" (panel on top and bottom), and put the WindowIconList
 applet on the bottom panel, the thumbnails aren't shown. (It seems to try to show the thumbnails below the mouse pointer, which, when the panel is at the bottom, is outside the screen). It works fine when the applet is on the panel at the top. 
(Cinnamon 2.4.6 on Archlinux 64bit)

**Comment by jake-phy** [comment]
I have that fixed in the dev version.  If you don't want to download the git version, just restart cinnamon after moving it to the bottom.  It should work correctly then.

-----Original Message-----

**Comment by anandtrex** [comment]
Can confirm that restarting Cinnamon works. Thanks!
