### ISSUE TITLE
Icons sticking to mouse on hover

### ISSUE THREAD

**Issue by zythaera** [jake-phy/WindowIconList#92]
Random window icons are sticking to the mouse as the mouse hovers over top as if it thinks I'm moving the icon. I also seem to need to double click on the icons to open the app. 

I have tested many different mice and each one has the same issue.

![image](https://cloud.githubusercontent.com/assets/3145310/7303939/bfed1650-e9a8-11e4-8899-92856312b266.png)

**Comment by stefan123t** [comment]
This sounds like #91 move pinned apps has no threshold to me.
Thanks for reporting, maybe we can get some more attention on this problem.
I suspect it has something to do the way cinnamon acts on events.

Here are some references to similar issues in Cinnamon that have been resolved.
https://github.com/linuxmint/Cinnamon/issues/3116
https://github.com/linuxmint/Cinnamon/commit/27d0c9c4cfdf614b97534987d8f06517dcd31959
https://github.com/linuxmint/Cinnamon/issues/3109

Lester kindly mentioned that it may have something to do with the way this is handled in Configurable-Menu which WindowIconList is derived from.
https://github.com/lestcape/Configurable-Menu/issues/50

Kind regards,
Stefan

**Comment by mbacou** [comment]
This is a dup of https://github.com/jake-phy/WindowIconList/issues/100

**Comment by jake-phy** [comment]
This should be fixed now.
