### ISSUE TITLE
[Feature request] One element without select list when thumbnail is off

### ISSUE THREAD

**Issue by iro88** [jake-phy/WindowIconList#93]
Select list is useless when thumbinails is off and there is single app.

**Comment by Quadina** [comment]
Vote! :+1:

**Comment by jake-phy** [comment]
pretty much, however I have that there for the people that don't want to group the icons.

**Comment by jake-phy** [comment]
So it actually is useful.  think multiple firefox windows open.  hide the thumbs and stack vertically.  Looks and acts just how I want it to.
