### ISSUE TITLE
Cinnamon 2.6

### ISSUE THREAD

**Issue by dschaefer79** [jake-phy/WindowIconList#95]
Hi,

Apparently WindowIconList doesn't work well with cinnamon 2.6, are you planing to correct the bug with cinnamon 2.6 ?

Thanks,

Dominique Schaefer

**Comment by dschaefer79** [comment]
It figured out to make it working, but when I pin an app, it's very slow

**Comment by inf3rno** [comment]
Can you be more specific? I have 2.6 too and the applet works mostly well except some small bugs.

**Comment by jake-phy** [comment]
the latest dev version should work fine.
