### ISSUE TITLE
How to remove the square when mouse hover an un-opened app?

### ISSUE THREAD

**Issue by wzhy90** [jake-phy/WindowIconList#99]
![deepinscreenshot20150715200935](https://cloud.githubusercontent.com/assets/2318890/8699950/a789c2e6-2b3b-11e5-8c8c-4c365b06fc0e.png)
Like this....
I have not opened the terminal, but when mouse hover the icon, it will show a small square on the top

**Comment by jake-phy** [comment]
Yes that was a problem on the old version, I have that fixed in the git now.
